<div>
	<ul id="menu">
		<!--<li><a href = " "><img class="img7" src="images/logo.jpg" alt="Group's logo"></a></li>-->
		<li><a href="index.php">Home</a>
	<ul>
		<li class="gelatine"><a href="#what">What is it?</a></li>
	</ul>
		</li>
		<li><a href="topic.php">Description</a>
			<ul>
				<li class="gelatine"><a href="topic.php#about">About Bootstrap</a></li>
				<li class="gelatine"><a href="topic.php#why">Why use it?</a></li>
				<li class="gelatine"><a href="topic.php#development">Developing Bootstrap</a></li>
				<li class="gelatine"><a href="topic.php#structure">Bootstrap File Structure</a></li>
				<li class="gelatine"><a href="topic.php#tools">Bootstrap Tools</a></li>
				<li class="gelatine"><a href="topic.php#competitors">Competitors</a></li>
				<li class="gelatine"><a href="topic.php#future"> Future of Bootstrap</a></li>
			</ul>
		</li>
		<li><a href="history.php">History</a></li>
		<li><a href="quiz.php">Quiz</a>
			<ul>
				<li class="gelatine"><a href="login.php">Supervisor</a></li>
			</ul>
		</li>

		<li><a href="enhancements.php">Enhancements</a></li>
		<li><a href="phpenhancements.php">PHP Enhancements</a></li>
		<li><a href="references.php">References</a></li>
	</ul>
</div>

		
